### ISSUE TITLE
Unable to load joint_state_broadcaster or the joint_trajectory_controller

### ISSUE THREAD

**Issue by VineetTambe** [ros-controls/gazebo_ros2_control#200]
Hey,

I am trying to integrate gazebo ros2 control with my project in order to control a revolute joint.
I have followed the position control example - [test_cart_position.xacro.urdf](https://github.com/ros-controls/gazebo_ros2_control/blob/master/gazebo_ros2_control_demos/urdf/test_cart_position.xacro.urdf)

And have used this config file: [cartpole_controller.yaml](https://github.com/ros-controls/gazebo_ros2_control/blob/master/gazebo_ros2_control_demos/config/cartpole_controller.yaml)

However, when I try to load the joint_state_broadcaster via ros2controlcli I get controller not found error.
```
$ ros2 control load_controller --set-state active joint_state_broadcaster

Error loading controller, check controller_manager logs


Loading controller 'joint_state_broadcaster'
[gzserver-1] [ERROR] [1684965811.371939215] [controller_manager]: Loader for controller 'joint_state_broadcaster' (type 'joint_state_broadcaster/JointStateBroadcaster') not found.
[gzserver-1] [INFO] [1684965811.371987660] [controller_manager]: Available classes:
[gzserver-1] [INFO] [1684965811.372027368] [controller_manager]:   controller_manager/test_controller
[gzserver-1] [INFO] [1684965811.372064919] [controller_manager]:   controller_manager/test_controller_failed_init
[gzserver-1] [INFO] [1684965811.372101259] [controller_manager]:   controller_manager/test_controller_with_interfaces
[gzserver-1] [INFO] [1684965811.372138974] [controller_manager]:   controller_manager/test_chainable_controller

```

And the only available controllers are as follows:
```
ros2 control list_controller_types 
controller_manager/test_controller                                     controller_interface::ControllerInterface
controller_manager/test_controller_failed_init                         controller_interface::ControllerInterface
controller_manager/test_controller_with_interfaces                     controller_interface::ControllerInterface
controller_manager/test_chainable_controller                           controller_interface::ChainableControllerInterface
```
This is how I define my joint and gazebo plugin in the urdf.
```
<joint name="body_to_lid_revolute" type="revolute">
      <origin xyz="-0.175 0 0.125"/>
      <axis xyz="0 1 0"/>
      <parent link="${parent}"/>
      <child link="${name}"/>
      <limit lower="-1.571" upper="0" effort="100" velocity="0.1"/>
    </joint>

    <ros2_control name="GazeboSystem" type="system">
      <hardware>
        <plugin>gazebo_ros2_control/GazeboSystem</plugin>
      </hardware>
      <joint name="body_to_lid_revolute">
        <command_interface name="position">
          <param name="min">-1.571</param>
          <param name="max">0.0</param>
        </command_interface>
        <state_interface name="position">
          <param name="initial_value">0.0</param>
        </state_interface>
        <state_interface name="velocity"/>
        <state_interface name="effort"/>
      </joint>
    </ros2_control>

    <gazebo>
      <plugin filename="libgazebo_ros2_control.so" name="gazebo_ros2_control">
        <robot_param>robot_description</robot_param>
        <robot_param_node>${namespace}/robot_state_publisher/robot_state_publisher</robot_param_node>
        <parameters>$(find don_description)/config/lid_joint_controller.yaml</parameters>
      </plugin>
    </gazebo>
```
This is how I have defined my `yaml` file:
```
controller_manager:
  ros__parameters:
    update_rate: 100 # Hz

    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

joint_trajectory_controller:
  ros__parameters:
    joints:
      - body_to_lid_revolute
    interface_name: position
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity

```

I don't understand what is the missing piece here! Can anyone help me out here! Thanks in advance!
